BEGIN TRY

BEGIN TRAN;

-- CreateTable
CREATE TABLE [dbo].[PublicRelay] (
    [id] INT NOT NULL IDENTITY(1,1),
    [url] NVARCHAR(1000) NOT NULL,
    [isActive] BIT NOT NULL,
    [createdAt] DATETIME2 NOT NULL,
    [notes] NVARCHAR(1000),
    CONSTRAINT [PublicRelay_pkey] PRIMARY KEY CLUSTERED ([id])
);

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
