openapi: 3.0.1
info:
  title: NIP05.social API
  version: 1.0.0
  description: NIP05.social API
  termsOfService: https://example.com/terms
  contact:
    name: Chris
    url: https://nip05.social
    email: chris@iijat.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: http://localhost:4000/v1
  description: Local server
- url: https://nip05api.azurewebsites.net/v1
  description: Production server
tags:
- name: CRUD operations
paths:
  /registrations:
    get:
      description: Get all registrations.
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: 'components/schemas/registration-dto.yaml#/RegistrationDto'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: 'components/schemas/error.yaml#/Error'
              example:
                message: Authorization information is missing or invalid.
  /registration/{id}:
    get:
      description: Get a single registration by its id.
      parameters:
      - name: id
        in: path
        schema:
          type: string
        required: true
        description: Registration id
        example: 5f4e4b2b-3b4d-4b5d-8f93-6c260f1f3d1d
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: 'components/schemas/registration-dto.yaml#/RegistrationDto'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: 'components/schemas/error.yaml#/Error'
              example:
                message: Authorization information is missing or invalid.
        '404':
          description: A registration with the specified id was not found.
          content:
            application/json:
              schema:
                $ref: 'components/schemas/error.yaml#/Error'
              example:
                message: A registration with the id 5f4e4b2b-3b4d-4b5d-8f93-6c260f1f3d1d was not found.
    patch:
      description: Update a registration by its id.
      parameters:
      - name: id
        in: path
        schema:
          type: string
        required: true
        description: Registration id
        example: 5f4e4b2b-3b4d-4b5d-8f93-6c260f1f3d1d
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: 'components/schemas/registration-patch-dto.yaml#/RegistrationPatchDto'
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: 'components/schemas/registration-dto.yaml#/RegistrationDto'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: 'components/schemas/error.yaml#/Error'
              example:
                message: Authorization information is missing or invalid.
        '404':
          description: A registration with the specified id was not found.
          content:
            application/json:
              schema:
                $ref: 'components/schemas/error.yaml#/Error'
              example:
                message: A registration with the id 5f4e4b2b-3b4d-4b5d-8f93-6c260f1f3d1d was not found.
        '500':
          description: An error occurred while updating the registration.
          content:
            application/json:
              schema:
                $ref: 'components/schemas/error.yaml#/Error'
              example:
                message: An error occurred while updating the registration.
  /check/is-available/{id}:
    get:
      description: Check if a nostr address is available.
      parameters:
      - name: id
        in: path
        schema:
          type: string
        required: true
        description: Nostr address
        example: frank@protonostr.com
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: 'components/schemas/is-available-dto.yaml#/IsAvailableDto'
        '400':
          description: Bad request.
          content:
            application/json:
              schema:
                $ref: 'components/schemas/error.yaml#/Error'
              example:
                message: Please provide a valid nostr address.
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: 'components/schemas/error.yaml#/Error'
              example:
                message: An error occurred while checking if the nostr address is available.
  /register/request:
    $ref: 'register/request.yaml#/~1register~1request'
  /register/redeem:
    $ref: 'register/redeem.yaml#/~1register~1redeem'
security:
- bearerAuth: []
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
  schemas:
    Error:
      $ref: 'components/schemas/error.yaml#/Error'
    IsAvailableDto:
      $ref: 'components/schemas/is-available-dto.yaml#/IsAvailableDto'
    RegisterRequestPostDto:
      $ref: 'components/schemas/register-request-post-dto.yaml#/RegisterRequestPostDto'
    RegisterRequestResponseDto:
      $ref: 'components/schemas/register-request-response-dto.yaml#/RegisterRequestResponseDto'
    RegisterRedeemPostDto:
      $ref: 'components/schemas/register-redeem-post-dto.yaml#/RegisterRedeemPostDto'
    RegisterRedeemResponseDto:
      $ref: 'components/schemas/register-redeem-response-dto.yaml#/RegisterRedeemResponseDto'
    RegistrationDto:
      $ref: 'components/schemas/registration-dto.yaml#/RegistrationDto'
    RegistrationPatchDto:
      $ref: 'components/schemas/registration-patch-dto.yaml#/RegistrationPatchDto'
    UserTokenDto:
      $ref: 'components/schemas/user-token-dto.yaml#/UserTokenDto'
